# Generated by Django 2.2 on 2019-04-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('is_directory', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(max_length=50000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file.File')),
            ],
        ),
    ]
